export const USER_SIGNED_IN = "USER_SIGNED_IN";
export const USER_SIGNED_OUT = "USER_SIGNED_OUT";
export const REFRESH_ACCOUNT = "REFRESH_ACCOUNT";


// Lookup data
export const UPDATE_COUNTRY_LIST = "UPDATE_COUNTRY_LIST";
export const UPDATE_PROVINCE_LIST = "UPDATE_PROVINCE_LIST";
export const UPDATE_CITY_LIST = "UPDATE_CITY_LIST";
export const UPDATE_CATEGORIES_LIST = "UPDATE_CATEGORIES_LIST";
export const UPDATE_SUB_CATEGORIES_LIST = "UPDATE_SUB_CATEGORIES_LIST";
export const TRANSACTION_VALUE_LIST = "TRANSACTION_VALUE_LIST";
export const TRANSACTION_NUMBER_LIST = "TRANSACTION_NUMBER_LIST";
export const UPDATE_OCCUPATION_GROUP_LIST = "UPDATE_OCCUPATION_GROUP_LIST";
export const UPDATE_OCCUPATION_LIST = "UPDATE_OCCUPATION_LIST";

// Business Account
export const UPDATE_REGISTRATION_DATA = "UPDATE_REGISTRATION_DATA";
